### ISSUE TITLE
Body class disappear

### ISSUE THREAD

**Issue by Troglos** [Pijushgupta/avif-express#6]
When logged in, the body class disappear.

Not logged: <body class="home page-template-default page page-id-2">
Logged: <body>

**Comment by Pijushgupta** [comment]
> When logged in, the body class disappear.
> 
> Not logged: Logged:

can you please describe little more about the issue ?

**Comment by Troglos** [comment]
Sorry the editor stripped the code.

The problem I was having was:
When I am not logged in the body has the correct classes handled by WP: es. home page-template-default page page-id-2
When I am logged as admin the body has no classes

By the way I just found the cause, it was this function in my custom theme:

if (current_user_can('manage_options')) {
    add_action('wp_head', 'show_template');
    function show_template()
    {
        global $template;
        print_r($template);
    }
}

**Comment by Pijushgupta** [comment]
> Sorry the editor stripped the code.
> 
> The problem I was having was: When I am not logged in the body has the correct classes handled by WP: es. home page-template-default page page-id-2 When I am logged as admin the body has no classes
> 
> By the way I just found the cause, it was this function in my custom theme:
> 
> if (current_user_can('manage_options')) { add_action('wp_head', 'show_template'); function show_template() { global $template; print_r($template); } }

how to related to avif-express? is this something to do with rendering [html.php](https://github.com/Pijushgupta/avif-express/blob/main/core/app/frontend/Html.php)

**Comment by Troglos** [comment]
When avif-express is activated and rendering is Active, with that function uncommented I have the issue.
If rendering is Inactive or if I comment that code the issue disappear.
Anyway it's not a big deal, because I can easily comment that function on a live site.

**Comment by Pijushgupta** [comment]
So it not related to avif-express code? We are doing the rendering at the very last moment [html.php](https://github.com/Pijushgupta/avif-express/blob/main/core/app/frontend/Html.php) on line 15 then using  [output buffer ](https://www.php.net/manual/en/function.ob-start.php) on line 19.

To use your custom code while plugins rendering is active try giving print_r() a second parameter with the value 'true'. By setting the second parameter to true, print_r will return the output as a string instead of printing it directly. 
`
if (current_user_can('manage_options')) { 
add_action('wp_head', 'show_template'); 
}
function show_template() { 
global $template; print_r($template,true); 
} `

**Comment by Troglos** [comment]
For styling purpose I use a div to wrap print_r($template), so your suggestion unfortunately doesn't work.
I solved replacing wp_head with wp_footer.
Thank you for the input
